### PR TITLE
removed synonyms/cross references to OMIM:250100 Metachromatic Leukod…

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
On MONDO_0009591 'metachromatic leukodystrophy, juvenile form', I removed synonyms/cross references to OMIM:250100 'Metachromatic Leukodystrophy, Adult' and 'Metachromatic Leukodystrophy, Late Infantile'

### CODE REVIEW

**Comment by cmungall** [comment]
image

did you use Protege? What format did you save as?

**Comment by nicolevasilevsky** [comment]
yes, I used Protege. I think it saved it as an OBO file? I just did file->save

**Comment by cmungall** [comment]
Can you show a sample. On phone can't check diff

**Comment by nicolevasilevsky** [comment]
Sorry, I wasn't checking the diff before committing the changes on the branch - I'll know to do that going forward!

I just made a change on a term so I could check the diff (just added a test comment), here is an example of the diff:

image

**Comment by nicolevasilevsky** [comment]
here is another example of a diff (I didn't commit this):
image

I will hold off on PRs until this is resolved (as you said in another ticket). Thank you for your help!

**Comment by cmungall** [comment]
That looks like a nice well behaved diff! You can go ahead and make PRs for
ones like this.

**Pull request closed without merging**
