### PR TITLE
added synonym to MONDO_0020467 Mosaic monosomy X

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
added synonym 'Mosaic Turner Syndrome' to MONDO_0020467 Mosaic monosomy X

addresses #62

I am getting crazy diffs. I remember that Protege used to do this a lot when I was editing the eagle-i  ontology back in day, and Carlo said not to worry about it.

@cmungall please let me know if this is an issue, or if I am doing something wrong.
Thank you!

### CODE REVIEW

**Comment by cmungall** [comment]
Hi @nicolevasilevsky - can you avoid making a PR on this repo if the diff is larger than expected. The diff should only show lines that have changed in a human readable format. It's like you're saving something other than obo

**Comment by nicolevasilevsky** [comment]
Ok, apologies!
I don't know why the file is being saved in a weird format. I'm following the instructions in the mondo editors document. Have you had this problem before or do you have any troubleshooting suggestions?

**Comment by cmungall** [comment]
the first tip is to do a `git diff` before committing.

Do an experiment. Load mondo-edit.obo. Make a minor change. Save (not Save-as). Is it different?

**Comment by nicolevasilevsky** [comment]
Yeah, I am getting these crazy diffs, even with a minor change:
image

this is only part of it

**Comment by cmungall** [comment]
ok, that's enough info for me. Looks like owltools is using a different version of the owlapi from robot and protege. I will handle this.

**Comment by nicolevasilevsky** [comment]
Great- glad you were able to diagnose the issue! Thank you, Chris!

**Comment by nicolevasilevsky** [comment]
Hi @cmungall - were you able to solve this issue? Should I try to add the synonym again?

**Pull request closed without merging**
